Fix an FTBFS under -Werror=return-type
Some Linux distributions globally build with -Werror=return-type, to
catch garbage returns from functions. process() could be called with
a garbage RPCType value, in which case it would run off the end of
the function since there is no `default:` case, and return new
garbage.

```
rpc/rpc_manager.cc: In member function ‘bool rpc::RpcManager::process(RPCType, const char*, uint32_t, slot_response_callback)’:
rpc/rpc_manager.cc:119:1: error: control reaches end of non-void function [-Werror=return-type]
  119 | }
rpc/rpc_manager.cc: In member function ‘bool rpc::RpcManager::is_type_enabled(RPCType) const’:
rpc/rpc_manager.cc:143:1: error: control reaches end of non-void function [-Werror=return-type]
  143 | }
```